### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by chris-morgan** [idanarye/rust-typed-builder#15]
This crate is licensed MIT, but it would be helpful for it to be MIT/Apache-2.0. Rather than copying all the text explaining why and how and such, I’ll just link to https://github.com/shepmaster/jetscii/issues/12 as the first such auto-generated issue that came to hand.

There are commits from three people so far:

- Almost all of the code is from @idanarye. Your permission will therefore be required to relicense.

- I, @chris-morgan, have one commit (and several more locally that I’ll submit soon). I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

- @Bert-Proesmans has 2587d6fe9038fdf4b4abdac68d39fc679385e5ef, which is mechanical in nature and therefore probably excluded from copyright. Receiving permission to relicense from this user would be ideal for clarity, but I don’t think it’s necessary.

@idanarye, it’d be nice if you were willing to do this. There’s guidance and instructions in the linked issue.

**Comment by idanarye** [comment]
I couldn't care less what the license is, as long as it's open-source and not GPL. I picked MIT because it seemed the most permissive and compatible-with-anything based on the diagram in https://janelia-flyem.github.io/licenses.html, but I wouldn't mind dual-licensing it.

Gonna wait a few more days to see if @Bert-Proesmans replies.

**Comment by idanarye** [comment]
BTW - do proc-macro crates even matter when it comes to copyleft? After all, their code does not really get into the actual program - they generate new code that does. So doesn't that make them the same as compilers, that don't pass their copyleft to the produced binaries?

**Comment by chris-morgan** [comment]
I believe generated code is a grey area, because it often does include copyrightable portions—but deciding what’s what is left to the lawyers. Compilers are completely general-purpose, and merely applying patterns to your own code, which doesn’t give any scope for copyright; some proc macros will be acting like that, but others will be adding concrete, potentially copyrightable stuff to your code. My guess for this crate would be that it’s sufficiently compilery that the only part that might matter would be strings in the generated documentation that are copied verbatim rather than calculated, and there’s not much of that anyway.

But I find it easiest to simply make sure that all the stuff I’m using is MIT/Apache-2.0 or similar, and acknowledge all things used, even if they’re not strictly necessary. That way I *know* I’m safe. Well, as much as you ever can know such things with software licensing.

**Comment by Bert-Proesmans** [comment]
I didn't respond at first because I believe my additions to this library are exempt from relicensing discussion.

To be explicit; I share the same opinion as @idanarye where all my open source contributions are written without much thought about licensing. MIT seemed ok in my book for the purposes to show off my "mad programmer skillz" and contribute to the world.

I agree with relicensing my contributions to MIT/Apache-2.0 dual license.
