### ISSUE TITLE
Default arguments to use `default`!

### ISSUE THREAD

**Issue by wdanilo** [idanarye/rust-typed-builder#18]
Hi! I'd love to ask why the fields without any metadata are not using `default` automatically. In almost all cases my structs are written with `// #[builder(default)]` every second line. Isn't this the most common use case for the builder pattern?

**Comment by idanarye** [comment]
I don't believe so. The main point of this crate is to ensure that you have set all mandatory fields at compile time (unlike [derive_builder](https://crates.io/crates/derive_builder), that does it at runtime and you have to `unwrap()` the result). If all fields had a default by default, this would have been pointless. Sure, it'd still warn you about setting the same field twice - but that's easy to spot while noticing a missing field is hard.

Now, I could do it and add `#[builder(mandatory)]` to opt out field, but as a rule I'd rather err on the side of caution - if you missed a `#[builder(default)]` you'll notice it pretty soon when some `build()` gets rejected, but missing a `#[builder(mandatory)]` could result in a logical error when you forget to set the field, `build()` still works, and the field is set to its default instead of what its supposed to be.

**Comment by wdanilo** [comment]
@idanarye thanks for the explanation. I would still prefer the other way around, but this discussion would base too strong on personal preferences, so it would rather not make much sense. Thank you again for expressing your opinions. Closing this topic for now! :)
