### ISSUE TITLE
Add strip_option attribute

### ISSUE THREAD

**Issue by mwilliammyers** [idanarye/rust-typed-builder#19]
Nice crate! 

It would be super handy to have an option to strip `Option` in addition to being generic over `Into` like [`derive-builder`](https://github.com/colin-kiegel/rust-derive-builder#usage-and-features).

Example:

```rust
#[derive(TypedBuilder)]
struct User {
    id: String,
    #[builder(strip_option)]
    name: Option<String>,
}

User::builder().id("id").name("bob").build();
```

instead of having to do:
```rust
User::builder().id("id").name(Some("bob".to_string())).build();
```

What do you think?

**Comment by idanarye** [comment]
Semantically, this would only make sense for non-mandatory fields. `.name(None)` won't work, because the argument type of `name` is `String` ([assuming we remove the auto-`into()`](https://www.reddit.com/r/rust/comments/eqjktn/community_thoughts_about_introducing_a_breaking/feufnzd/)), so the only way to use the builder to create a nameless user is to make `name` `#[builder(default, strip_option)]`, and not call its setter.

So, I wonder what's the best way to extern this in the API.

* Disallow `strip_option` without a `default`?
* Automatically add a `default`? (maybe pick a name the better represents this?)
* Add a `name_none()` setter? (yea, that's probably a bad idea)

I also had this idea for an aggregating field. Something like:
```rust
#[derive(TypedBuilder)]
struct Foo {
    #[builder(collect)]
    numbers: Vec<i32>,
}

assert_eq!(
    Foo::builder().number(1).number(2).number(3).build(),
    vec![1, 2, 3]);
```
(yea, I probably want to avoid the singular-plural hell...)

This might be related to your idea, because `Option` in Rust (and FP in general) can be treated as a collection of zero or one items.

Then again - with `Option` we want to disable the setter after the first invocation, so maybe this is not such a good idea...

**Comment by idanarye** [comment]
I also don't really like the name `strip_option`. It implies that something is an `Option` and you are converting it to non-`Option`, when in practice it's the other way around (you are accepting something that is not `Option` and converting it to `Option`)

This flag is similar to the auto-into flag (which's name is also yet to be decided), so maybe it's a good idea to give them similar names? Like `#[builder(auto_into)]` and `#[builder(auto_some)]` (since we are automatically slapping `Some()` on the argument)? Or maybe, since `into()` makes `Some()` redundant, I should unite them to `#[builder(auto=into)]` and `#[builder(auto=Some)]`?

**Comment by idanarye** [comment]
Well, I kind of missed that `derive-builder` uses that name. Since they made a precedent, I'll use that name too - though I'm going to want to make it `#[builder(setter(strip_option))]` if I want to have the same interface.
