### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by emosenkis** [idanarye/rust-typed-builder#3]
To get better error messages that just "not found" you could implement the missing methods but have them take an argument whose name is the error message. It's not pretty, but at least somewhere in the "wrong number of args" error message there would be a hint about the actual issue.

**Comment by idanarye** [comment]
@TedDriggs - your approach won't work, because if two fields are missing I'll have two deprecated `build()` methods, and the compiler won't allow that.

I don't think @emosenkis' approach will work either, because I'm not using traits here (don't want to force the user to import a preamble for every `TypedBuilder` struct they use) and having multiple methods with the same name but different signatures on the same struct (not via traits) is method overloading - which Rust does not support.

**Comment by idanarye** [comment]
Done in #30 by @seb-bl.
