### ISSUE TITLE
Handle deprecated fields

### ISSUE THREAD

**Issue by mauricelam** [idanarye/rust-typed-builder#76]
If I have a deprecated field in my struct, the generated `TypedBuilder` has two unexpected behavior:

1. It complains about the used of deprecated fields in the definition, but adding `#[allow(deprecated)]` on the struct doesn't help (because it's used in a separate, generated block?)
2. The generated setter is not marked as deprecated, so users of the builder won't know that they are setting a deprecated field.

Example:

```rs
#[allow(deprecated)]
#[derive(Debug, TypedBuilder)]
pub struct StringConfig {
    #[deprecated(note="Do not use.")]
    #[builder(default = true)]
    pub save: bool,
}
```

**Comment by mo8it** [comment]
That should be easy. We need to add `#[allow(deprecated)]` to the last line of `build()` where in this example `StringConfig { save }.into()` is called.

Why is there an `.into()` btw?

Then we need to add the same deprecation note of the field `save` to the method `save`.

Do we want to throw a compilation error if the default attribute is not set?

@idanarye Can I give it a try for a PR?

**Comment by idanarye** [comment]
@mo8it Go for it.

The `into`, BTW, is because of #80. It did cause a problem for #84, so I'll have to make it conditional on whether or not `#[builder(build_method(into))]` is used, but there are other things blocking #84 so I leave it in [its branch](https://github.com/idanarye/rust-typed-builder/tree/feature/issue-84-allow-const-builder) for now.
